"""
Figures for the analysis chapter. Each function takes a DataFrame and writes a
PNG. Women figures use `load_women()` output; the women/total ratio additionally
needs `load_corpus()`.

All figures are regenerated by `rosenwald/analysis/run_all.py`.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

_W_COLOR = "#b5179e"
_M_COLOR = "#4361ee"


def _save(fig, out: Path) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def women_per_year(women: pd.DataFrame, out: Path) -> Path:
    """Number of women practitioners per volume year."""
    s = women.dropna(subset=["annee_volume"]).groupby("annee_volume").size()
    fig, ax = plt.subplots(figsize=(11, 4))
    ax.bar(s.index.astype(int), s.values, color=_W_COLOR)
    ax.set_xlabel("Année du volume"); ax.set_ylabel("Femmes recensées")
    ax.set_title("Femmes médecins par année (Guides Rosenwald)")
    return _save(fig, out)


def women_by_list_type(women: pd.DataFrame, out: Path) -> Path:
    """Count of women by list type."""
    s = women.groupby("list_type").size().sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.barh(s.index, s.values, color=_W_COLOR)
    ax.set_xlabel("Femmes recensées"); ax.set_title("Femmes par type de liste")
    return _save(fig, out)


def women_evolution_by_list(women: pd.DataFrame, out: Path, lists=("paris_quartiers", "deps_cantons")) -> Path:
    """Evolution of women counts over time for the two main lists."""
    fig, ax = plt.subplots(figsize=(11, 4))
    for lt in lists:
        sub = women[(women["list_type"] == lt)].dropna(subset=["annee_volume"])
        s = sub.groupby("annee_volume").size()
        ax.plot(s.index.astype(int), s.values, marker="o", label=lt)
    ax.set_xlabel("Année du volume"); ax.set_ylabel("Femmes")
    ax.set_title("Évolution des femmes par liste principale"); ax.legend()
    return _save(fig, out)


def top_female_specialties(women: pd.DataFrame, out: Path, top: int = 12) -> Path:
    """Most frequent specialties among women (specialistes list)."""
    spec = women[(women["list_type"] == "specialists") & (women["specialite"] != "")]
    s = spec["specialite"].str.upper().value_counts().head(top).sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.barh(s.index, s.values, color=_W_COLOR)
    ax.set_xlabel("Femmes"); ax.set_title(f"Top {top} spécialités féminines")
    return _save(fig, out)


def women_by_department(women: pd.DataFrame, out: Path, top: int = 15) -> Path:
    """Top departments by number of women (deps_cantons + seine_cantons)."""
    geo = women[women["list_type"].isin(["deps_cantons", "seine_cantons"])]
    geo = geo[geo["departement"] != ""]
    s = geo["departement"].str.upper().value_counts().head(top).sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(9, 6))
    ax.barh(s.index, s.values, color=_W_COLOR)
    ax.set_xlabel("Femmes"); ax.set_title(f"Top {top} départements (femmes)")
    return _save(fig, out)


def diploma_year_distribution(women: pd.DataFrame, out: Path) -> Path:
    """Distribution of women's diploma years."""
    s = women.dropna(subset=["annee_diplome"])
    s = s[(s["annee_diplome"] >= 1850) & (s["annee_diplome"] <= 1925)]
    fig, ax = plt.subplots(figsize=(11, 4))
    ax.hist(s["annee_diplome"].astype(int), bins=range(1850, 1926, 2), color=_W_COLOR)
    ax.set_xlabel("Année de diplôme"); ax.set_ylabel("Femmes")
    ax.set_title("Distribution des années de diplôme (femmes)")
    return _save(fig, out)


def women_by_profession(women: pd.DataFrame, out: Path) -> Path:
    """Distinct women per profession category (docteur / pharmacien / officier)."""
    key = women["nom"].str.strip().str.lower() + "|" + women["prenom"].str.strip().str.lower()
    s = (women.assign(_k=key).groupby("profession_cat")["_k"].nunique()
         .drop(labels=["non précisé"], errors="ignore").sort_values(ascending=True))
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.barh(s.index, s.values, color=_W_COLOR)
    for i, v in enumerate(s.values):
        ax.text(v, i, f" {int(v)}", va="center")
    ax.set_xlabel("Praticiennes distinctes"); ax.set_title("Femmes par profession")
    return _save(fig, out)


def women_ratio_by_year(women: pd.DataFrame, corpus: pd.DataFrame, out: Path) -> Path:
    """Women as a share of all practitioners per year (needs corpus)."""
    if corpus.empty:
        raise ValueError("corpus is empty — load_corpus() needs data/tsv_clean")
    w = women.dropna(subset=["annee_volume"]).groupby("annee_volume").size()
    t = corpus.groupby("year").size()
    years = sorted(set(w.index.astype(int)) | set(int(y) for y in t.index))
    ratio = [100 * w.get(y, 0) / t.get(y, 1) for y in years]
    fig, ax = plt.subplots(figsize=(11, 4))
    ax.plot(years, ratio, marker="o", color=_W_COLOR)
    ax.set_xlabel("Année"); ax.set_ylabel("% de femmes")
    ax.set_title("Proportion de femmes parmi les praticiens")
    return _save(fig, out)


WOMEN_ONLY = {
    "women_per_year": women_per_year,
    "women_by_list_type": women_by_list_type,
    "women_evolution_by_list": women_evolution_by_list,
    "top_female_specialties": top_female_specialties,
    "women_by_department": women_by_department,
    "diploma_year_distribution": diploma_year_distribution,
    "women_by_profession": women_by_profession,
}
